#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/garbage.h"
#include "images/walter.h"
#include "images/start.h"
#include "images/start2.h"
#include "images/bb.h"
#include "images/ba.h"
#include "images/tortuga.h"
#include "images/tortuga2.h"
#include "images/gameoverani/ww1.h"
#include "images/gameoverani/ww2.h"
#include "images/gameoverani/ww3.h"
#include "images/gameoverani/ww4.h"
#include "images/gameoverani/ww5.h"
#include "images/gameoverani/ww6.h"
#include "images/gameoverani/ww7.h"
#include "images/gameoverani/ww8.h"
#include "images/gameoverani/ww9.h"
#include "images/gameoverani/ww10.h"
#include "images/gameoverani/ww11.h"
#include "images/gameoverani/ww12.h"
#include "images/gameoverani/ww13.h"
#include "images/gameoverani/ww14.h"
#include "images/gameoverani/ww15.h"
#include "images/gameoverani/ww16.h"
#include "images/gameoverani/ww17.h"
#include "images/gameoverani/ww18.h"
#include "images/gameoverani/ww19.h"
#include "images/gamewinani/bb1.h"
#include "images/gamewinani/bb2.h"
#include "images/gamewinani/bb3.h"
#include "images/gamewinani/bb4.h"
#include "images/gamewinani/bb5.h"
#include "images/gamewinani/bb6.h"
#include "images/gamewinani/bb7.h"
#include "images/jesse.h"
#include "images/jessuh.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  INTRO,
  CHARACTER_SELECT, 
  WALT, 
  JESSE,
  PLAY,
  WIN, W2, W3, W4, W5, W6, W7,
  LOSE, L2, L3, L4, L5, L6, L7,L8, L9, L10,
  L11, L12, L13, L14, L15, L16, L17, L18, L19
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  videoBuffer[1208] = 0x7fff;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();
    switch (state) {
      case START: ;
        int bby = 0;
        int bay = 135;
        while (bby <=75 && bay >=100) {
          drawFullScreenImageDMA(start);
          drawImageDMA(bby, 75, 25, 25, bb);
          drawImageDMA(bay, 100, 25, 25, ba);
          bby++;
          bay--;
          waitForVBlank();
          if (bay == 100) {
            break;
          }
        }
        state = INTRO;
        waitForVBlank();
        break;
case INTRO: ;

  struct tort t;
  t.tx = 10;
  t.ty = 130;

  int move_right = 1; 

  while (1) {
    currentButtons = BUTTONS;
    if (KEY_DOWN(BUTTON_START, currentButtons)) {
                  state = CHARACTER_SELECT;
                  break;
              }
              

    if (move_right) {
      t.tx += 2; // move right
    } else {
      t.tx -= 2; // move left
    }


    if (t.tx >= 220) {
      move_right = 0; 
    } else if (t.tx <= 10) {
      move_right = 1; 
    }
    if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            waitForVBlank();
            break;
    }
    drawFullScreenImageDMA(start2);
    drawImageDMA(75, 75, 25, 25, bb);
    drawImageDMA(100, 100, 25, 25, ba);
    drawImageDMA(t.ty, t.tx, 20, 20, tortuga);
    drawChar(115, 125, 'd', BLACK);

  waitForVBlank();
  } 
  waitForVBlank();
  break;
      case CHARACTER_SELECT:
      waitForVBlank();
        currentButtons = BUTTONS;
            drawFullScreenImageDMA(jesse);
            waitForVBlank();
            drawString(100, 100, "Select a character", BLACK);
            waitForVBlank();
            drawString(130,60, "Jesse", YELLOW);
            waitForVBlank();
            drawString(130,120, "Waltuh", BLACK);
            waitForVBlank();
            waitForVBlank();
            if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            break;
        }
            for (u32 i = 0; i < 500 * 1000; i++) {
              currentButtons = BUTTONS;
              if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            waitForVBlank();
            break;
            }
                if (KEY_DOWN(BUTTON_A, BUTTONS)) {
                state = JESSE;
                waitForVBlank();
                break;
            } 
            if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
                state = WALT;
                waitForVBlank();
                break;
        }
            }
            waitForVBlank();
            break;
        case WALT: ;
        waitForVBlank();
        currentButtons = BUTTONS;
            drawFullScreenImageDMA(ww1);
            waitForVBlank();
            drawString(100, 100, "Select a character", BLACK);
            waitForVBlank();
            drawString(130,60, "Jesse", BLACK);
            waitForVBlank();
            drawString(130,120, "Waltuh", YELLOW);
            waitForVBlank();
            waitForVBlank();
            for (u32 i = 0; i < 500 * 1000; i++) {
              currentButtons = BUTTONS;
                if (KEY_DOWN(BUTTON_A, BUTTONS)) {
                state = PLAY;
                waitForVBlank();
                break;
            } 
            if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            waitForVBlank();
            break;
            }
            if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
                state = CHARACTER_SELECT;
                waitForVBlank();
                break;
        }
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            break;
        }
            }
            waitForVBlank();
            break;
case JESSE: ;
int timer = 300;

    struct jussuh j;
    j.jesseX = 0;
    j.jesseY = 125;
    int jesseSpeed = 3;
    int jesseJumpSpeed = 5;
    int jesseJumpHeight = 40;
    int jesseJumpCount = 0;
    int isJumping = 0;

    u16 previousButtons = BUTTONS;
    u16 currentButtons = BUTTONS;

    while (1) {

        previousButtons = currentButtons;
        currentButtons = BUTTONS;

        timer--;
        if (timer <= 0) {
            state = LOSE;
            break;
        }

        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            break;
        }
        if (j.jesseX >=220 && j.jesseY < 130) {
            state = WIN;
            break;
        }

        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
            j.jesseX -= jesseSpeed;
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
            j.jesseX += jesseSpeed;
        }


        if (j.jesseX < 0) {
            j.jesseX = 0;
        }
        if (j.jesseX + 54 > WIDTH) {
            j.jesseX = WIDTH - JESSUH_WIDTH;
        }
        if (isJumping == 1) {
            j.jesseY -= jesseJumpSpeed;
            jesseJumpCount += jesseJumpSpeed;
            if (jesseJumpCount >= jesseJumpHeight) {
                isJumping = 0;
                jesseJumpCount = 0;
            }
        } else {

            j.jesseY += 10;
            if (j.jesseY + JESSUH_HEIGHT >= 140) {
                j.jesseY = 140 - JESSUH_HEIGHT ;
            }
        }

        if (KEY_DOWN(BUTTON_A, currentButtons) && !KEY_DOWN(BUTTON_A, previousButtons)) {
            if (isJumping == 0) {
                isJumping = 1;
            }
        }

        

        fillScreenDMA(BLACK);
        drawRectDMA(140, 0, WIDTH, 5, WHITE);
        drawImageDMA(j.jesseY, j.jesseX, JESSUH_WIDTH, JESSUH_HEIGHT, jessuh);
        drawRectDMA(130, 220, 1, 5, BLUE);
        char timeStr[20];
        snprintf(timeStr, 20, "Time: %d", timer/60);
        drawString(150, 10, timeStr, WHITE);
        drawString(150, 100, "Get Blue", WHITE);
        waitForVBlank();
    }

    if (state == START) {
        timer = 600;
    }
    break;
case PLAY: ;


    int timer2 = 300;

    struct walt w;
    w.walterX = 0;
    w.walterY = 125;
    int walterSpeed = 2;
    int walterJumpSpeed = 5;
    int walterJumpHeight = 40;
    int walterJumpCount = 0;
    int isJumping1 = 0;

    while (1) {

        previousButtons = currentButtons;
        currentButtons = BUTTONS;

        timer2--;
        if (timer2 <= 0) {
            state = LOSE;
            break;
        }

        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            break;
        }
        if (w.walterX >=220) {
            state = WIN;
            break;
        }

        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
            w.walterX -= walterSpeed;
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
            w.walterX += walterSpeed;
        }


        if (w.walterX < 0) {
            w.walterX = 0;
        }
        if (w.walterX + 54 > WIDTH) {
            w.walterX = WIDTH - WALTER_WIDTH;
        }
        if (isJumping1 == 1) {
            w.walterY -= walterJumpSpeed;
            walterJumpCount += walterJumpSpeed;
            if (walterJumpCount >= walterJumpHeight) {
                isJumping1 = 0;
                walterJumpCount = 0;
            }
        } else {

            w.walterY += 10;
            if (w.walterY + WALTER_HEIGHT >= 140) {
                w.walterY = 140 - WALTER_HEIGHT;
            }
        }

        if (KEY_DOWN(BUTTON_A, currentButtons) && !KEY_DOWN(BUTTON_A, previousButtons)) {
            if (isJumping1 == 0) {
                isJumping1 = 1;
            }
        }

        

        fillScreenDMA(BLACK);
        drawRectDMA(140, 0, WIDTH, 5, WHITE);
        drawImageDMA(w.walterY, w.walterX, WALTER_WIDTH, WALTER_HEIGHT, walter);
        drawRectDMA(130, 220, 1, 5, BLUE);
        char timeStr2[20];
        snprintf(timeStr2, 20, "Time: %d", timer2/60);
        drawString(150, 10, timeStr2, WHITE);
        drawString(150, 100, "Get Blue", WHITE);
        waitForVBlank();
    }

    if (state == START) {
        timer = 600;
    }
    break;
      case WIN:
        drawFullScreenImageDMA(bb1);
        drawString(130, 100, "GAMEWON", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = W2;
        break;
        case W2:
        drawFullScreenImageDMA(bb2);
        drawString(130, 100, "GAMEWON", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
        for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = W3;
        break;
      case W3:
        drawFullScreenImageDMA(bb3);
        drawString(130, 100, "GAMEWON", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
        for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = W4;
        break;
      case W4:
        drawFullScreenImageDMA(bb4);
        drawString(130, 100, "GAMEWON", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
        for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }

        state = W5;
        break;
      case W5:
        drawFullScreenImageDMA(bb5);
        drawString(130, 100, "GAMEWON", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = W6;
        break;
      case W6:
        drawFullScreenImageDMA(bb6);
        drawString(130, 100, "GAMEWON", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = W7;
        break;
      case W7:
        drawFullScreenImageDMA(bb7);
        drawString(130, 100, "GAMEWON", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = WIN;
        break;
      case LOSE:
        drawFullScreenImageDMA(ww1);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L2;
        break;
      case L2:
        drawFullScreenImageDMA(ww2);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
        for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L3;
        break;
      case L3:
        drawFullScreenImageDMA(ww3);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
        for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L4;
        break;
      case L4:
        drawFullScreenImageDMA(ww4);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
        for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }

        state = L5;
        break;
      case L5:
        drawFullScreenImageDMA(ww5);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L6;
        break;
      case L6:
        drawFullScreenImageDMA(ww6);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L7;
        break;
      case L7:
        drawFullScreenImageDMA(ww7);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L8;
        break;
      case L8:
        drawFullScreenImageDMA(ww8);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L9;
        break;
      case L9:
        drawFullScreenImageDMA(ww9);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L10;
        break;
      case L10:
        drawFullScreenImageDMA(ww10);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L11;
        break;
      case L11:
        drawFullScreenImageDMA(ww11);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L12;
        break;
      case L12:
        drawFullScreenImageDMA(ww12);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L13;
        break;
      case L13:
        drawFullScreenImageDMA(ww13);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L14;
        break;
      case L14:
        drawFullScreenImageDMA(ww14);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L15;
        break;
      case L15:
        drawFullScreenImageDMA(ww15);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L16;
        break;
      case L16:
        drawFullScreenImageDMA(ww16);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L17;
        break;
      case L17:
        drawFullScreenImageDMA(ww17);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L18;
        break;
      case L18:
        drawFullScreenImageDMA(ww18);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = L19;
        break;
      case L19:
        drawFullScreenImageDMA(ww19);
        drawString(130, 100, "GAMEOVER", WHITE);
        currentButtons = BUTTONS;
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                  state = START;
                  break;
              }
        // state = ?
      for (u32 i = 0; i < 500 * 75; i++) {
        // Do nothing, just wait
        }
        state = LOSE;
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
